import React, { createContext, useContext, useState, useEffect } from "react";
import { playClickSound } from "../utils/audioUtils";

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
];

const TRANSLATIONS = {
  en: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "Dashboard",
    "nav.new_decision": "New Decision",
    "nav.memory_vault": "Past Lessons",
    "nav.profile": "Profile & Values",
    "nav.about": "How It Works",
    "nav.sign_out": "Sign Out",
    "nav.convening": "Board Meeting In Progress",

    // Dashboard HUD
    "dash.welcome_title": "Make Better Decisions",
    "dash.welcome_desc": "Get six AI advisors to look at your choices from different points of view, discuss the risks, and suggest a clear next step.",
    "dash.btn_new": "+ Add a Decision",
    "dash.total_dilemmas": "Your Decisions",
    "dash.binding_verdicts": "Recommendations Made",
    "dash.premortem_acc": "Risk Check Accuracy",
    "dash.vector_learnings": "Past Lessons",
    "dash.filter_all": "All Decisions",
    "dash.filter_career": "Career & Transitions",
    "dash.filter_startup": "Startup & Venture",
    "dash.filter_engineering": "Tech & Engineering",
    "dash.filter_financial": "Financial & Capital",
    "dash.enter_boardroom": "▶ View Decision",
    "dash.no_dilemmas": "No decisions found in this category.",
    "dash.no_dilemmas_sub": "Add a decision to get advice from your six AI advisors.",

    // Boardroom & Live Debate
    "board.title": "AI Advisor Meeting",
    "board.live_session": "Your six AI advisors are discussing this decision...",
    "board.dialectic": "Comparing the benefits, risks, and trade-offs",
    "board.play_debate": "Start Discussion",
    "board.pause_debate": "Pause Discussion",
    "board.restart": "Restart",
    "board.memo_md": "Memo (.md)",
    "board.export_pdf": "Export PDF 🖨️",
    "board.consensus_index": "Advisor Agreement",
    "board.speaking_now": "Speaking Now",
    "board.final_verdict": "FINAL RECOMMENDATION",
    "board.consensus_score": "Agreement Score",
    "board.inspect_blueprint": "See the Full Action Plan Below ↓",

    // New Dilemma Page
    "new.title": "Get Advice on a Decision",
    "new.desc": "Tell us about a decision you are facing. Six AI advisors will compare your choices and recommend a path forward.",
    "new.dilemma_label": "Decision Title",
    "new.dilemma_placeholder": "e.g., Should I leave Big Tech to become founding engineer at an AI startup?",
    "new.context_label": "Background and Important Details",
    "new.context_placeholder": "Share the details that matter, such as money, timing, goals, limits, and risks...",
    "new.options_label": "Choices You Are Considering",
    "new.add_option": "+ Add Another Choice",
    "new.category_label": "Decision Type",
    "new.btn_convene": "Ask the AI Advisors ➔",
    "new.convening": "Your AI advisors are reviewing the decision...",

    // Profile Page
    "profile.title": "Your Profile and Values",
    "profile.desc": "Add your experience, comfort with risk, and personal values so the advisors can give more relevant advice.",
    "profile.resume_title": "Read Your Resume with AI",
    "profile.resume_desc": "Upload a PDF or paste your resume so we can find your experience, skills, and values.",
    "profile.extract_btn": "Read Profile with AI ⚡",
    "profile.extracting": "Reading Resume...",
    "profile.save_btn": "Save Profile",
    "profile.custom_seats": "Add Your Own Advisors",
    "profile.add_seat": "+ Add an Advisor",

    // Chat Copilot
    "chat.title": "DecisionOS Boardroom Copilot",
    "chat.placeholder": "Ask your AI advisors a question...",
    "chat.send": "Send",

    // Hero Section
    "hero.badge": "Six AI Advisors, One Clear Recommendation",
    "hero.headline": "Big decisions are easier",
    "hero.headline_accent": "with more than one point of view.",
    "hero.desc": "DecisionOS gives you six AI advisors: a business leader, finance expert, technology expert, risk checker, personal mentor, and final reviewer. They look at your choices, discuss what could go wrong, and give you a practical action plan.",
    "hero.btn_convene": "Get Advice on a Decision",
    "hero.btn_explore": "See Your Decisions",
    "hero.feat1_title": "6 Autonomous AI Advisors",
    "hero.feat1_desc": "Separate views on money, technology, growth, personal goals, and risk.",
    "hero.feat2_title": "Find Problems Before They Happen",
    "hero.feat2_desc": "The risk advisor checks how your plan could fail and what you can do about it.",
    "hero.feat3_title": "Remember What You Learn",
    "hero.feat3_desc": "Save the results of past decisions so future advice can use what you have learned.",

    // New Decision Form (extended)
    "new.back": "Back to Dashboard",
    "new.load_template": "Load Template:",
    "new.tmpl_startup": "Startup vs Big Tech",
    "new.tmpl_founder": "Founder Transition",
    "new.heading": "Tell Us About Your Decision",
    "new.heading_desc": "Share the decision and choices you are considering. Six AI advisors will review them, discuss the pros and cons, and suggest what to do next.",
    "new.field_title": "Decision or Question *",
    "new.field_context": "Background and Details *",
    "new.field_category": "Decision Category",
    "new.field_urgency": "Urgency",
    "new.field_risk": "Risk Tolerance",
    "new.field_goal": "Main Goal",
    "new.field_runway": "Available Financial Safety Net",
    "new.options_heading": "Your Choices",
    "new.options_desc": "List the choices you want the AI advisors to compare.",
    "new.opt_label": "Choice Name",
    "new.opt_desc": "What this choice means",
    "new.opt_pros": "Benefits",
    "new.opt_cons": "Risks",
    "new.add_pro": "+ Add a Benefit",
    "new.add_con": "+ Add a Risk",
    "new.remove_option": "Remove Option",

    // Memory Vault
    "vault.title": "Past Lessons",
    "vault.desc": "Save what happened after your decisions. When you face a similar choice later, your AI advisors can use these past lessons.",
    "vault.search_placeholder": "Search past decisions and lessons...",
    "vault.search_btn": "Search",
    "vault.scanning": "Loading past lessons...",
    "vault.empty_title": "No Past Lessons Yet",
    "vault.empty_desc": "After you record what happened, your notes will appear here and help with future decisions.",
    "vault.choice_label": "Choice You Made",
    "vault.outcome_label": "What Happened",
    "vault.lesson_label": "What You Learned",
    "vault.satisfaction": "Satisfaction",

    // About Page
    "about.badge": "Platform Guide",
    "about.title": "How DecisionOS Works",
    "about.desc": "DecisionOS gives you six AI advisors who look at difficult life and work decisions from different points of view.",
    "about.get_started": "Add Your First Decision →",
    "about.step1_title": "Describe Your Decision",
    "about.step1_desc": "Tell us what you need to decide, what matters to you, and which choices you are considering.",
    "about.step1_tag": "Input Stage",
    "about.step2_title": "Get Six Different Views",
    "about.step2_desc": "Each AI advisor looks at your decision from a different angle, such as money, technology, growth, or personal values.",
    "about.step2_tag": "Different Views",
    "about.step3_title": "Compare the Advice",
    "about.step3_desc": "The advisors point out weak spots in the plan. A final reviewer brings their advice together into one clear recommendation and action plan.",
    "about.step3_tag": "Clear Recommendation",
    "about.step4_title": "Record What Happened",
    "about.step4_desc": "Come back later and record the result. Your past experience can then improve future advice.",
    "about.step4_tag": "Learn Over Time",
    "about.advisors_title": "Meet Your 6 AI Advisors",
    "about.faq_title": "Frequently Asked Questions",

    // Decision Detail Page
    "detail.back": "Back to Executive Dashboard",
    "detail.loading": "Summoning Personal Board of Directors Briefing...",
    "detail.not_found": "Decision not found.",
    "detail.back_dash": "Back to Dashboard",
    "detail.verdict_rendered": "Verdict Rendered",
    "detail.awaiting": "Waiting for Advice",
    "detail.urgency": "Urgency",
    "detail.risk_profile": "Risk Profile",
    "detail.timeline": "Timeline",
    "detail.log_retro": "Log Retrospective Outcome",
    "detail.update_retro": "Update Retrospective",
    "detail.reconvene": "Ask Again",
    "detail.convene_boardroom": "Start AI Review",
    "detail.deliberating": "Advisors Are Reviewing...",
    "detail.tab_report": "Recommendation and Action Plan",
    "detail.tab_opinions": "Each Advisor's View",
    "detail.tab_debate": "Advisor Discussion",
    "detail.tab_chat": "Ask Follow-up Questions",
    "detail.board_standby": "Your AI Advisors Are Ready",
    "detail.board_standby_desc": "Start the review to see how the CEO, CFO, CTO, Risk Analyst, Mentor, and Chairman look at your decision and compare the choices.",
    "detail.convene_now": "Start AI Review Now",
    "detail.deliberating_6": "Six AI advisors are reviewing your choices...",

    // Profile Page (extended)
    "profile.heading": "Executive Profile & Core Values",
    "profile.heading_desc": "These baseline parameters guide your Personal Board of Directors (CEO, CFO, CTO, Risk Analyst, Mentor) across every strategic deliberation.",
    "profile.resume_extractor": "AI Resume & Bio Auto-Extractor",
    "profile.resume_extractor_desc": "Upload your resume or paste your career bio to automatically extract your role, 3-5 year goals, risk profile, and core values.",
    "profile.upload_file": "Upload File",
    "profile.paste_text": "Paste Text",
    "profile.drag_drop": "Click to select or drag & drop your Resume",
    "profile.file_formats": "Supports PDF, DOCX, TXT, MD",
    "profile.paste_placeholder": "Paste your resume text or LinkedIn 'About & Experience' section here...",
    "profile.extract_info": "⚡ Extracted parameters populate the form below and can be manually edited.",
    "profile.auto_extract": "Auto-Extract & Populate Profile",
    "profile.extracting_params": "Extracting Parameters...",
    "profile.extract_success": "Profile Ingestion Complete!",
    "profile.params_title": "Strategic Parameters & Manual Controls",
    "profile.params_desc": "Customize and fine-tune your parameters manually.",
    "profile.manual_active": "MANUAL EDITING ACTIVE",
    "profile.current_role": "Current Professional Role & Domain Focus",
    "profile.career_goals_label": "Career Goals & 5-Year Vision",
    "profile.financial_runway_label": "Financial Safety Runway",
    "profile.risk_tolerance_label": "Default Risk Tolerance",
    "profile.core_values_label": "Core Values & Operating Principles",
    "profile.add_value_placeholder": "Add a core value...",
    "profile.add_value_btn": "+ Add Value",
    "profile.personal_context_label": "Personal Context & Life Situation",
    "profile.save_success": "Strategic Profile & Core Values saved successfully.",
    "profile.saving": "Saving...",

    // Login Page
    "auth.login_title": "Welcome Back",
    "auth.login_subtitle": "Sign in to your DecisionOS cockpit",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.sign_in": "Sign In",
    "auth.signing_in": "Authenticating...",
    "auth.demo": "Demo Login",
    "auth.no_account": "No account?",
    "auth.sign_up_link": "Create one →",
    "auth.fill_fields": "Please fill in both email and password.",

    // Register Page
    "auth.register_title": "Join DecisionOS",
    "auth.register_subtitle": "Create your executive AI board account",
    "auth.full_name": "Full Name",
    "auth.confirm_pass": "Confirm Password",
    "auth.create_account": "Create Account",
    "auth.creating": "Creating Account...",
    "auth.have_account": "Already have an account?",
    "auth.sign_in_link": "Sign in →",

    // Outcome Logger Modal
    "outcome.title": "Log Retrospective Outcome",
    "outcome.subtitle": "Record what actually happened — this gets embedded into your AI board's long-term memory.",
    "outcome.choice_label": "Which option did you actually choose?",
    "outcome.period_label": "How long ago did you make this decision?",
    "outcome.satisfaction_label": "Satisfaction Score",
    "outcome.outcome_label": "What actually happened? (Realized Outcome)",
    "outcome.outcome_placeholder": "Describe the real-world outcome, performance, and how it played out vs. the board's prediction...",
    "outcome.lesson_label": "Key Lesson Learned (for future board sessions)",
    "outcome.lesson_placeholder": "What would you do differently? What assumptions were wrong or right?",
    "outcome.save": "Save Retrospective to Memory",
    "outcome.saving": "Embedding to Vector Memory...",
    "outcome.close": "Close",

    // Debate Timeline
    "debate.title": "Cross-Examination Debate Log",
    "debate.subtitle": "The live dialectic debate where advisors challenge each other's assumptions.",
    "debate.empty": "No debate turns recorded yet.",
    "debate.empty_desc": "Run the board deliberation to generate the cross-examination debate.",
    "debate.turn": "Turn",
    "debate.challenge": "Challenge",
    "debate.rebuttal": "Rebuttal",
  },

  hi: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "कॉकपिट (डैशबोर्ड)",
    "nav.new_decision": "नया असमंजस (Dilemma)",
    "nav.memory_vault": "स्मृति वॉल्ट (Memory)",
    "nav.profile": "प्रोफ़ाइल और मूल्य",
    "nav.about": "यह कैसे काम करता है (How It Works)",
    "nav.sign_out": "साइन आउट",
    "nav.convening": "सक्रिय बोर्ड सत्र",

    // Dashboard HUD
    "dash.welcome_title": "कार्यकारी निर्णय इंटेलिजेंस",
    "dash.welcome_desc": "6-सलाहकार मल्टी-एजेंट बहस इंजन जो वित्तीय रनवे, करियर गति और जोखिम का विश्लेषण करता है।",
    "dash.btn_new": "+ बोर्ड की बैठक बुलाएं",
    "dash.total_dilemmas": "कुल असमंजस",
    "dash.binding_verdicts": "अंतिम बाध्यकारी निर्णय",
    "dash.premortem_acc": "प्री-मॉर्टम सटीकता",
    "dash.vector_learnings": "ChromaDB सीख",
    "dash.filter_all": "सभी असमंजस",
    "dash.filter_career": "करियर और परिवर्तन",
    "dash.filter_startup": "स्टार्टअप और उद्यम",
    "dash.filter_engineering": "तकनीक और इंजीनियरिंग",
    "dash.filter_financial": "वित्तीय और पूंजी",
    "dash.enter_boardroom": "▶ लाइव बोर्डरूम में प्रवेश करें",
    "dash.no_dilemmas": "इस श्रेणी में कोई रणनीतिक निर्णय नहीं मिला।",
    "dash.no_dilemmas_sub": "6-सलाहकार बोर्ड की बैठक शुरू करने के लिए एक असमंजस जोड़ें।",

    // Boardroom & Live Debate
    "board.title": "कार्यकारी बोर्ड सत्र",
    "board.live_session": "लाइव मल्टी-एजेंट बोर्डरूम जारी है...",
    "board.dialectic": "सक्रिय बहस: 6 रणनीतिक आयामों पर परस्पर जिरह",
    "board.play_debate": "लाइव बहस शुरू करें",
    "board.pause_debate": "बहस रोकें",
    "board.restart": "पुनः प्रारंभ",
    "board.memo_md": "मेमो (.md)",
    "board.export_pdf": "PDF निर्यात 🖨️",
    "board.consensus_index": "बोर्डरूम सर्वसम्मति सूचकांक",
    "board.speaking_now": "अभी बोल रहे हैं",
    "board.final_verdict": "अंतिम बोर्डरूम संकल्प एवं निर्देश",
    "board.consensus_score": "सर्वसम्मति स्कोर",
    "board.inspect_blueprint": "नीचे पूर्ण रणनीति देखें ↓",

    // New Dilemma Page
    "new.title": "कार्यकारी बोर्ड की बैठक बुलाएं",
    "new.desc": "अपने 6 सलाहकारों द्वारा गहन जांच के लिए एक महत्वपूर्ण असमंजस दर्ज करें।",
    "new.dilemma_label": "रणनीतिक असमंजस का शीर्षक",
    "new.dilemma_placeholder": "उदा. क्या मुझे AI स्टार्टअप में फाउंडिंग इंजीनियर बनने के लिए बिग टेक छोड़ना चाहिए?",
    "new.context_label": "संदर्भ और सीमाएं",
    "new.context_placeholder": "वित्तीय रनवे, वेतन, इक्विटी, जोखिम सहनशीलता और मुख्य व्यापार-बंद का वर्णन करें...",
    "new.options_label": "विचाराधीन विकल्प",
    "new.add_option": "+ वैकल्पिक विकल्प जोड़ें",
    "new.category_label": "रणनीतिक कार्यक्षेत्र",
    "new.btn_convene": "पूरा बोर्ड सत्र शुरू करें (LangGraph) ➔",
    "new.convening": "सलाहकार समानांतर में विचार-विमर्श कर रहे हैं...",

    // Profile Page
    "profile.title": "कार्यकारी प्रोफ़ाइल और व्यक्तिगत मूल्य",
    "profile.desc": "अपने बोर्ड ऑफ डायरेक्टर्स को अपने अनुभव, जोखिम प्रोफ़ाइल और मूल्यों के अनुसार कैलिब्रेट करें।",
    "profile.resume_title": "AI रेज़्यूमे और अनुभव विश्लेषक",
    "profile.resume_desc": "अनुभव, कौशल और मूल्यों को स्वचालित रूप से निकालने के लिए PDF अपलोड करें या टेक्स्ट पेस्ट करें।",
    "profile.extract_btn": "AI द्वारा प्रोफ़ाइल निकालें ⚡",
    "profile.extracting": "रेज़्यूमे का विश्लेषण जारी...",
    "profile.save_btn": "प्रोफ़ाइल सहेजें",
    "profile.custom_seats": "कस्टम बोर्ड सीटें और सलाहकार",
    "profile.add_seat": "+ नया सलाहकार सीट बनाएं",

    // Chat Copilot
    "chat.title": "DecisionOS बोर्डरूम सहायक",
    "chat.placeholder": "अपने AI बोर्ड से तुरंत रणनीतिक सलाह पूछें...",
    "chat.send": "भेजें",

    // Hero Section
    "hero.badge": "मल्टी-एजेंट रणनीतिक इंटेलिजेंस",
    "hero.headline": "उच्च-दांव वाले निर्णयों के लिए जरूरी है",
    "hero.headline_accent": "विविध दृष्टिकोण।",
    "hero.desc": "एक सिंगल AI प्रॉम्प्ट की जगह, DecisionOS 6 स्वायत्त कार्यकारी सलाहकार (CEO, CFO, CTO, जोखिम विश्लेषक, मेंटर, चेयरमैन) को समानांतर में बहस कराकर सर्वश्रेष्ठ रणनीति बनाता है।",
    "hero.btn_convene": "नई बोर्ड बैठक बुलाएं",
    "hero.btn_explore": "सक्रिय बहसें देखें",
    "hero.feat1_title": "6 स्वायत्त AI सलाहकार",
    "hero.feat1_desc": "वित्तीय रनवे, तकनीक गति, असममित लाभ और जोखिम सुरक्षा पर समानांतर मूल्यांकन।",
    "hero.feat2_title": "प्री-मॉर्टम जोखिम ऑडिट",
    "hero.feat2_desc": "व्यवस्थित विफलता बिंदुओं की पहचान और निष्पादन से पहले 90-दिन की चेतावनी।",
    "hero.feat3_title": "ChromaDB दीर्घकालिक स्मृति",
    "hero.feat3_desc": "पिछले निर्णयों के वास्तविक अनुभव को इंडेक्स कर भविष्य की सलाह को परिष्कृत करता है।",

    // New Decision Form (extended)
    "new.back": "डैशबोर्ड पर वापस",
    "new.load_template": "टेम्पलेट लोड करें:",
    "new.tmpl_startup": "स्टार्टअप बनाम बिग टेक",
    "new.tmpl_founder": "फाउंडर ट्रांजिशन",
    "new.heading": "अपना पर्सनल बोर्ड ऑफ डायरेक्टर्स बुलाएं",
    "new.heading_desc": "अपना रणनीतिक असमंजस और विकल्प दर्ज करें। AI बोर्ड (CEO, CFO, CTO, जोखिम विश्लेषक, मेंटर, चेयरमैन) विश्लेषण, बहस और सिफारिश करेगा।",
    "new.field_title": "निर्णय असमंजस / प्रश्न *",
    "new.field_context": "पूरी पृष्ठभूमि और संदर्भ *",
    "new.field_category": "निर्णय श्रेणी",
    "new.field_urgency": "तात्कालिकता",
    "new.field_risk": "जोखिम सहनशीलता",
    "new.field_goal": "प्राथमिक रणनीतिक लक्ष्य",
    "new.field_runway": "वित्तीय आधार रनवे",
    "new.options_heading": "रणनीतिक विकल्प और विकल्पीय पथ",
    "new.options_desc": "वे वैकल्पिक रास्ते परिभाषित करें जिन पर बोर्ड ऑफ डायरेक्टर्स बहस और तुलना करेगा।",
    "new.opt_label": "विकल्प शीर्षक / नाम",
    "new.opt_desc": "रणनीतिक पथ का विवरण",
    "new.opt_pros": "फायदे / सकारात्मक पहलू",
    "new.opt_cons": "जोखिम / नकारात्मक पहलू",
    "new.add_pro": "+ फायदा जोड़ें",
    "new.add_con": "+ जोखिम जोड़ें",
    "new.remove_option": "विकल्प हटाएं",

    // Memory Vault
    "vault.title": "दीर्घकालिक स्मृति वॉल्ट",
    "vault.desc": "DecisionOS आपके पिछले निर्णयों, चुनावों और अनुभवों के वेक्टर एम्बेडिंग स्टोर करता है। नए असमंजस पर AI बोर्ड पुराने अनुभव से सीखकर बेहतर सलाह देता है।",
    "vault.search_placeholder": "असमंजस, सीख या करियर थीम से खोजें...",
    "vault.search_btn": "सिमेंटिक खोज",
    "vault.scanning": "ChromaDB वेक्टर वॉल्ट स्कैन हो रही है...",
    "vault.empty_title": "अभी कोई ऐतिहासिक स्मृति इंडेक्स नहीं है",
    "vault.empty_desc": "जब आप पूर्ण निर्णयों पर परिणाम लॉग करेंगे, तो आपके अनुभव भविष्य की बोर्ड बैठकों के लिए यहाँ स्वतः एम्बेड हो जाएंगे।",
    "vault.choice_label": "लिया गया निर्णय",
    "vault.outcome_label": "वास्तविक परिणाम",
    "vault.lesson_label": "बोर्ड के लिए मुख्य रणनीतिक सीख",
    "vault.satisfaction": "संतुष्टि",

    // About Page
    "about.badge": "सिस्टम आर्किटेक्चर",
    "about.title": "DecisionOS कैसे काम करता है",
    "about.desc": "एक मल्टी-एजेंट LangGraph ऑर्केस्ट्रेशन सिस्टम जहाँ 6 विशेषज्ञ AI सलाहकार स्वतंत्र रूप से आपके उच्च-दांव वाले निर्णयों पर विचार-विमर्श करते हैं।",
    "about.get_started": "अपना पहला बोर्ड बुलाएं →",
    "about.step1_title": "अपना रणनीतिक असमंजस परिभाषित करें",
    "about.step1_desc": "रास्ते का चुनाव तय करें। वित्तीय रनवे, जोखिम सहनशीलता, लक्ष्य और प्रतिस्पर्धी विकल्प निर्दिष्ट करें।",
    "about.step1_tag": "इनपुट चरण",
    "about.step2_title": "स्वायत्त बोर्ड बुलाएं",
    "about.step2_desc": "डिसीजन एनालाइज़र समानांतर में 5 विशेषज्ञ AI सलाहकारों को सक्रिय करता है। प्रत्येक एक कठोर मानसिक मॉडल लागू करता है।",
    "about.step2_tag": "समानांतर विचार-विमर्श",
    "about.step3_title": "जिरह और चेयरमैन का फैसला",
    "about.step3_desc": "सलाहकार एक-दूसरे की मान्यताओं को चुनौती देते हैं। चेयरमैन बाध्यकारी फैसला, आत्मविश्वास स्कोर और कार्य योजना तैयार करते हैं।",
    "about.step3_tag": "संश्लेषण",
    "about.step4_title": "वेक्टर मेमोरी में परिणाम दर्ज करें",
    "about.step4_desc": "वास्तव में क्या हुआ यह लॉग करें। परिणाम ChromaDB वेक्टर मेमोरी में एम्बेड होते हैं, जिससे भविष्य की बैठकें और स्मार्ट बनती हैं।",
    "about.step4_tag": "निरंतर सीखना",
    "about.advisors_title": "अपने 6 AI सलाहकारों से मिलें",
    "about.faq_title": "अक्सर पूछे जाने वाले प्रश्न",

    // Decision Detail Page
    "detail.back": "कार्यकारी डैशबोर्ड पर वापस",
    "detail.loading": "पर्सनल बोर्ड ऑफ डायरेक्टर्स की ब्रीफिंग तैयार हो रही है...",
    "detail.not_found": "निर्णय नहीं मिला।",
    "detail.back_dash": "डैशबोर्ड पर वापस",
    "detail.verdict_rendered": "फैसला सुनाया गया",
    "detail.awaiting": "विचार-विमर्श की प्रतीक्षा",
    "detail.urgency": "तात्कालिकता",
    "detail.risk_profile": "जोखिम प्रोफ़ाइल",
    "detail.timeline": "समयसीमा",
    "detail.log_retro": "पूर्वव्यापी परिणाम दर्ज करें",
    "detail.update_retro": "पूर्वव्यापी अपडेट करें",
    "detail.reconvene": "बोर्ड पुनः बुलाएं",
    "detail.convene_boardroom": "बोर्डरूम बुलाएं",
    "detail.deliberating": "कोरम विचार-विमर्श कर रहा है...",
    "detail.tab_report": "कार्यकारी फैसला और रणनीति",
    "detail.tab_opinions": "व्यक्तिगत सलाहकार स्कोरकार्ड",
    "detail.tab_debate": "जिरह बहस",
    "detail.tab_chat": "बोर्ड से प्रश्नोत्तर",
    "detail.board_standby": "बोर्ड ऑफ डायरेक्टर्स तैयार है",
    "detail.board_standby_desc": "LangGraph मल्टी-एजेंट सिमुलेशन शुरू करने के लिए नीचे क्लिक करें। CEO, CFO, CTO, जोखिम विश्लेषक और मेंटर आपके असमंजस का स्वतंत्र विश्लेषण करेंगे।",
    "detail.convene_now": "AI बोर्ड बैठक अभी बुलाएं",
    "detail.deliberating_6": "6 AI व्यक्तित्वों में विचार-विमर्श जारी...",

    // Profile Page (extended)
    "profile.heading": "कार्यकारी प्रोफ़ाइल और मूल मूल्य",
    "profile.heading_desc": "ये आधारभूत पैरामीटर हर रणनीतिक विचार-विमर्श में आपके पर्सनल बोर्ड (CEO, CFO, CTO, जोखिम विश्लेषक, मेंटर) का मार्गदर्शन करते हैं।",
    "profile.resume_extractor": "AI रेज़्यूमे और बायो ऑटो-एक्सट्रैक्टर",
    "profile.resume_extractor_desc": "अपनी भूमिका, 3-5 साल के लक्ष्य, जोखिम प्रोफ़ाइल और मूल मूल्यों को स्वचालित रूप से निकालने के लिए रेज़्यूमे अपलोड करें।",
    "profile.upload_file": "फ़ाइल अपलोड करें",
    "profile.paste_text": "टेक्स्ट पेस्ट करें",
    "profile.drag_drop": "रेज़्यूमे चुनने या ड्रैग करने के लिए क्लिक करें",
    "profile.file_formats": "PDF, DOCX, TXT, MD समर्थित",
    "profile.paste_placeholder": "अपना रेज़्यूमे टेक्स्ट या LinkedIn 'About & Experience' यहाँ पेस्ट करें...",
    "profile.extract_info": "⚡ निकाले गए पैरामीटर नीचे फॉर्म में भर जाएंगे और मैन्युअल रूप से संपादित किए जा सकते हैं।",
    "profile.auto_extract": "AI से प्रोफ़ाइल स्वचालित रूप से भरें",
    "profile.extracting_params": "पैरामीटर निकाले जा रहे हैं...",
    "profile.extract_success": "प्रोफ़ाइल इंजेशन पूर्ण!",
    "profile.params_title": "रणनीतिक पैरामीटर और मैन्युअल नियंत्रण",
    "profile.params_desc": "अपने पैरामीटर मैन्युअल रूप से कस्टमाइज़ और फ़ाइन-ट्यून करें।",
    "profile.manual_active": "मैन्युअल संपादन सक्रिय",
    "profile.current_role": "वर्तमान पेशेवर भूमिका और डोमेन फोकस",
    "profile.career_goals_label": "करियर लक्ष्य और 5-वर्षीय दृष्टि",
    "profile.financial_runway_label": "वित्तीय सुरक्षा रनवे",
    "profile.risk_tolerance_label": "डिफ़ॉल्ट जोखिम सहनशीलता",
    "profile.core_values_label": "मूल मूल्य और संचालन सिद्धांत",
    "profile.add_value_placeholder": "एक मूल मूल्य जोड़ें...",
    "profile.add_value_btn": "+ मूल्य जोड़ें",
    "profile.personal_context_label": "व्यक्तिगत संदर्भ और जीवन स्थिति",
    "profile.save_success": "रणनीतिक प्रोफ़ाइल और मूल मूल्य सफलतापूर्वक सहेजे गए।",
    "profile.saving": "सहेजा जा रहा है...",

    // Login Page
    "auth.login_title": "वापस स्वागत है",
    "auth.login_subtitle": "अपने DecisionOS कॉकपिट में साइन इन करें",
    "auth.email": "ईमेल पता",
    "auth.password": "पासवर्ड",
    "auth.sign_in": "साइन इन",
    "auth.signing_in": "प्रमाणीकरण जारी...",
    "auth.demo": "डेमो लॉगिन",
    "auth.no_account": "खाता नहीं है?",
    "auth.sign_up_link": "बनाएं →",
    "auth.fill_fields": "कृपया ईमेल और पासवर्ड दोनों भरें।",

    // Register Page
    "auth.register_title": "DecisionOS से जुड़ें",
    "auth.register_subtitle": "अपना कार्यकारी AI बोर्ड खाता बनाएं",
    "auth.full_name": "पूरा नाम",
    "auth.confirm_pass": "पासवर्ड की पुष्टि करें",
    "auth.create_account": "खाता बनाएं",
    "auth.creating": "खाता बनाया जा रहा है...",
    "auth.have_account": "पहले से खाता है?",
    "auth.sign_in_link": "साइन इन करें →",

    // Outcome Logger Modal
    "outcome.title": "पूर्वव्यापी परिणाम दर्ज करें",
    "outcome.subtitle": "वास्तव में क्या हुआ रिकॉर्ड करें — यह आपके AI बोर्ड की दीर्घकालिक स्मृति में एम्बेड होगा।",
    "outcome.choice_label": "आपने वास्तव में कौन सा विकल्प चुना?",
    "outcome.period_label": "यह निर्णय कब लिया था?",
    "outcome.satisfaction_label": "संतुष्टि स्कोर",
    "outcome.outcome_label": "वास्तव में क्या हुआ? (वास्तविक परिणाम)",
    "outcome.outcome_placeholder": "वास्तविक परिणाम का वर्णन करें और बोर्ड की भविष्यवाणी से तुलना करें...",
    "outcome.lesson_label": "मुख्य सीख (भविष्य की बोर्ड बैठकों के लिए)",
    "outcome.lesson_placeholder": "आप क्या अलग करते? कौन सी धारणाएं सही या गलत थीं?",
    "outcome.save": "स्मृति में पूर्वव्यापी सहेजें",
    "outcome.saving": "वेक्टर मेमोरी में एम्बेड हो रहा है...",
    "outcome.close": "बंद करें",

    // Debate Timeline
    "debate.title": "जिरह बहस लॉग",
    "debate.subtitle": "लाइव द्वंद्वात्मक बहस जहाँ सलाहकार एक-दूसरे की मान्यताओं को चुनौती देते हैं।",
    "debate.empty": "अभी कोई बहस दौर दर्ज नहीं है।",
    "debate.empty_desc": "जिरह बहस उत्पन्न करने के लिए बोर्ड विचार-विमर्श चलाएं।",
    "debate.turn": "दौर",
    "debate.challenge": "चुनौती",
    "debate.rebuttal": "खंडन",
  },

  es: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "Panel de Control",
    "nav.new_decision": "Nuevo Dilema",
    "nav.memory_vault": "Bóveda de Memoria",
    "nav.profile": "Perfil y Valores",
    "nav.about": "Cómo Funciona",
    "nav.sign_out": "Cerrar Sesión",
    "nav.convening": "Quórum Activo",

    // Dashboard HUD
    "dash.welcome_title": "Inteligencia de Decisiones Ejecutivas",
    "dash.welcome_desc": "Motor de debate dialéctico multi-agente que modela retorno asimétrico, riesgo financiero y velocidad.",
    "dash.btn_new": "+ Convocar Junta",
    "dash.total_dilemmas": "Dilemas Totales",
    "dash.binding_verdicts": "Veredictos Vinculantes",
    "dash.premortem_acc": "Precisión Pre-Mortem",
    "dash.vector_learnings": "Memoria ChromaDB",
    "dash.filter_all": "Todos los Dilemas",
    "dash.filter_career": "Carrera y Transiciones",
    "dash.filter_startup": "Startups y Empresas",
    "dash.filter_engineering": "Tecnología e Ingeniería",
    "dash.filter_financial": "Finanzas y Capital",
    "dash.enter_boardroom": "▶ Entrar a la Sala de Juntas",
    "dash.no_dilemmas": "No se encontraron dilemas estratégicos en esta categoría.",
    "dash.no_dilemmas_sub": "Envíe un dilema para convocar la junta directiva de 6 agentes.",

    // Boardroom & Live Debate
    "board.title": "Sesión de la Junta Directiva",
    "board.live_session": "Sesión de Junta Multi-Agente en Vivo...",
    "board.dialectic": "Dialéctica Activa: Contrainterrogatorio a través de 6 vectores estratégicos",
    "board.play_debate": "Iniciar Debate en Vivo",
    "board.pause_debate": "Pausar Debate",
    "board.restart": "Reiniciar",
    "board.memo_md": "Memorando (.md)",
    "board.export_pdf": "Exportar PDF 🖨️",
    "board.consensus_index": "Índice de Consenso",
    "board.speaking_now": "Hablando Ahora",
    "board.final_verdict": "RESOLUCIÓN Y DIRECTIVA FINAL DE LA JUNTA",
    "board.consensus_score": "Puntuación de Consenso",
    "board.inspect_blueprint": "Inspeccionar Plan de Acción Abajo ↓",

    // New Dilemma Page
    "new.title": "Convocar Junta Ejecutiva",
    "new.desc": "Presente un dilema de alto impacto para ser analizado por su junta de 6 agentes.",
    "new.dilemma_label": "Título del Dilema Estratégico",
    "new.dilemma_placeholder": "ej., ¿Debería dejar Big Tech para unirme a una startup de IA como ingeniero fundador?",
    "new.context_label": "Contexto y Limitaciones",
    "new.context_placeholder": "Describa el margen financiero, compensación, capital, tolerancia al riesgo...",
    "new.options_label": "Opciones Bajo Consideración",
    "new.add_option": "+ Agregar Opción Alternativa",
    "new.category_label": "Dominio Estratégico",
    "new.btn_convene": "Convocar Junta Completa (LangGraph) ➔",
    "new.convening": "Asesores Deliberando en Paralelo...",

    // Profile Page
    "profile.title": "Perfil Ejecutivo y Directivas",
    "profile.desc": "Calibre su junta directiva según su experiencia, tolerancia al riesgo y valores fundamentales.",
    "profile.resume_title": "Extractor de Currículum por IA",
    "profile.resume_desc": "Suba un PDF o pegue el texto de su CV para extraer automáticamente experiencia y valores.",
    "profile.extract_btn": "Extraer Perfil con IA ⚡",
    "profile.extracting": "Analizando Currículum...",
    "profile.save_btn": "Guardar Calibración",
    "profile.custom_seats": "Asesores Personalizados",
    "profile.add_seat": "+ Crear Asiento de Asesor",

    // Chat Copilot
    "chat.title": "Copiloto de la Junta DecisionOS",
    "chat.placeholder": "Pida consejo estratégico en tiempo real a su junta...",
    "chat.send": "Enviar",

    // Hero Section
    "hero.badge": "Inteligencia Estratégica Multi-Agente",
    "hero.headline": "Las decisiones de alto impacto requieren",
    "hero.headline_accent": "perspectivas diversas.",
    "hero.desc": "En lugar de un solo prompt de IA, DecisionOS orquesta 6 asesores ejecutivos autónomos (CEO, CFO, CTO, Analista de Riesgos, Mentor, Presidente) que analizan, debaten y sintetizan recomendaciones.",
    "hero.btn_convene": "Convocar Nueva Reunión de Junta",
    "hero.btn_explore": "Explorar Deliberaciones Activas",
    "hero.feat1_title": "6 Asesores IA Autónomos",
    "hero.feat1_desc": "Evaluaciones paralelas de runway financiero, velocidad tecnológica, upside asimétrico y salvaguardas de riesgo.",
    "hero.feat2_title": "Auditorías Pre-Mortem de Riesgo",
    "hero.feat2_desc": "Identifica modos de fallo sistémicos y establece alertas de 90 días antes de ejecutar.",
    "hero.feat3_title": "Memoria a Largo Plazo ChromaDB",
    "hero.feat3_desc": "Indexa lecciones retrospectivas del mundo real para refinar continuamente la orientación estratégica.",

    // New Decision Form (extended)
    "new.back": "Volver al Panel",
    "new.load_template": "Cargar Plantilla:",
    "new.tmpl_startup": "Startup vs Gran Empresa",
    "new.tmpl_founder": "Transición de Fundador",
    "new.heading": "Convoque su Junta Personal de Directores",
    "new.heading_desc": "Defina su dilema estratégico y opciones. Su Junta IA (CEO, CFO, CTO, Analista de Riesgos, Mentor, Presidente) analizará, debatirá y sintetizará una recomendación.",
    "new.field_title": "Dilema / Pregunta Estratégica *",
    "new.field_context": "Antecedentes y Contexto Completo *",
    "new.field_category": "Categoría de Decisión",
    "new.field_urgency": "Urgencia",
    "new.field_risk": "Tolerancia al Riesgo",
    "new.field_goal": "Objetivo Estratégico Principal",
    "new.field_runway": "Runway Financiero Base",
    "new.options_heading": "Opciones y Alternativas Estratégicas",
    "new.options_desc": "Defina los caminos alternativos que la Junta Directiva debatirá y comparará.",
    "new.opt_label": "Etiqueta / Nombre de Opción",
    "new.opt_desc": "Descripción del Camino Estratégico",
    "new.opt_pros": "Ventajas / Aspectos Positivos",
    "new.opt_cons": "Riesgos / Aspectos Negativos",
    "new.add_pro": "+ Agregar Ventaja",
    "new.add_con": "+ Agregar Riesgo",
    "new.remove_option": "Eliminar Opción",

    // Memory Vault
    "vault.title": "Bóveda de Memoria a Largo Plazo",
    "vault.desc": "DecisionOS almacena embeddings vectorizados de sus decisiones pasadas. Su Junta extrae sabiduría semántica para que nunca repita errores pasados.",
    "vault.search_placeholder": "Buscar por dilema, lección o tema de carrera...",
    "vault.search_btn": "Consulta Semántica",
    "vault.scanning": "Escaneando bóveda vectorial ChromaDB...",
    "vault.empty_title": "Aún No Hay Memorias Indexadas",
    "vault.empty_desc": "Una vez que registre resultados en decisiones completadas, sus reflexiones se incrustarán automáticamente aquí.",
    "vault.choice_label": "Decisión Ejecutada",
    "vault.outcome_label": "Resultado Real",
    "vault.lesson_label": "Lección Estratégica Clave para la Junta",
    "vault.satisfaction": "Satisfacción",

    // About Page
    "about.badge": "Arquitectura del Sistema",
    "about.title": "Cómo Funciona DecisionOS",
    "about.desc": "Un sistema de orquestación LangGraph multi-agente donde 6 asesores IA especializados deliberan independientemente sus decisiones de alto impacto.",
    "about.get_started": "Convoque su Primera Junta →",
    "about.step1_title": "Defina su Dilema Estratégico",
    "about.step1_desc": "Defina la encrucijada. Especifique restricciones como runway financiero, tolerancia al riesgo y opciones en competencia.",
    "about.step1_tag": "Etapa de Entrada",
    "about.step2_title": "Convoque la Junta Autónoma",
    "about.step2_desc": "El Analizador de Decisiones activa 5 asesores IA especializados en paralelo. Cada uno aplica un modelo mental riguroso.",
    "about.step2_tag": "Deliberación Paralela",
    "about.step3_title": "Contrainterrogatorio y Veredicto del Presidente",
    "about.step3_desc": "Los asesores desafían las suposiciones del otro. El Presidente sintetiza un veredicto vinculante y un plan de acción.",
    "about.step3_tag": "Síntesis",
    "about.step4_title": "Registrar Resultados en Memoria Vectorial",
    "about.step4_desc": "Registre lo que realmente sucedió. Los resultados se incrustan en ChromaDB, haciendo las futuras reuniones más inteligentes.",
    "about.step4_tag": "Aprendizaje Continuo",
    "about.advisors_title": "Conozca sus 6 Asesores IA",
    "about.faq_title": "Preguntas Frecuentes",
    "detail.back": "Volver al Panel Ejecutivo",
    "detail.loading": "Convocando Reunión de Junta Directiva...",
    "detail.not_found": "Decisión no encontrada.",
    "detail.back_dash": "Volver al Panel",
    "detail.verdict_rendered": "Veredicto Emitido",
    "detail.awaiting": "Esperando Deliberación",
    "detail.urgency": "Urgencia",
    "detail.risk_profile": "Perfil de Riesgo",
    "detail.timeline": "Cronograma",
    "detail.log_retro": "Registrar Resultado Retrospectivo",
    "detail.update_retro": "Actualizar Retrospectiva",
    "detail.reconvene": "Reconvocar Junta",
    "detail.convene_boardroom": "Convocar Sala de Juntas",
    "detail.deliberating": "Quórum Deliberando...",
    "detail.tab_report": "Veredicto Ejecutivo y Plan",
    "detail.tab_opinions": "Tarjetas de Puntuación de Asesores",
    "detail.tab_debate": "Debate de Contrainterrogatorio",
    "detail.tab_chat": "Preguntas a la Junta",
    "detail.board_standby": "La Junta Directiva Está Lista",
    "detail.board_standby_desc": "Haga clic para iniciar la simulación. El CEO, CFO, CTO, Analista de Riesgos y Mentor analizarán su dilema de forma independiente.",
    "detail.convene_now": "Convocar Reunión de Junta Ahora",
    "detail.deliberating_6": "Deliberando con 6 Personas IA...",
    "profile.heading": "Perfil Ejecutivo y Valores Fundamentales",
    "profile.heading_desc": "Estos parámetros guían a su Junta Personal en cada deliberación estratégica.",
    "profile.resume_extractor": "Extractor de CV e IA",
    "profile.upload_file": "Subir Archivo",
    "profile.paste_text": "Pegar Texto",
    "profile.drag_drop": "Haga clic o arrastre su CV aquí",
    "profile.file_formats": "PDF, DOCX, TXT, MD admitidos",
    "profile.auto_extract": "Auto-Extraer y Completar Perfil",
    "profile.extracting_params": "Extrayendo Parámetros...",
    "profile.extract_success": "¡Ingesta de Perfil Completa!",
    "profile.params_title": "Parámetros Estratégicos y Controles Manuales",
    "profile.params_desc": "Personalice y ajuste sus parámetros manualmente.",
    "profile.manual_active": "EDICIÓN MANUAL ACTIVA",
    "profile.current_role": "Rol Profesional Actual y Enfoque de Dominio",
    "profile.career_goals_label": "Metas de Carrera y Visión a 5 Años",
    "profile.financial_runway_label": "Runway Financiero de Seguridad",
    "profile.risk_tolerance_label": "Tolerancia al Riesgo Predeterminada",
    "profile.core_values_label": "Valores Fundamentales y Principios",
    "profile.add_value_btn": "+ Agregar Valor",
    "profile.personal_context_label": "Contexto Personal y Situación de Vida",
    "profile.save_success": "Perfil y Valores Fundamentales guardados correctamente.",
    "profile.saving": "Guardando...",
    "auth.login_title": "Bienvenido de Nuevo",
    "auth.login_subtitle": "Inicie sesión en su cabina DecisionOS",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.sign_in": "Iniciar Sesión",
    "auth.signing_in": "Autenticando...",
    "auth.demo": "Demo",
    "auth.no_account": "¿Sin cuenta?",
    "auth.sign_up_link": "Crear una →",
    "auth.register_title": "Únase a DecisionOS",
    "auth.register_subtitle": "Cree su cuenta de junta directiva IA",
    "auth.full_name": "Nombre Completo",
    "auth.confirm_pass": "Confirmar Contraseña",
    "auth.create_account": "Crear Cuenta",
    "auth.creating": "Creando Cuenta...",
    "auth.have_account": "¿Ya tiene cuenta?",
    "auth.sign_in_link": "Iniciar sesión →",
    "outcome.title": "Registrar Resultado Retrospectivo",
    "outcome.subtitle": "Registre lo que realmente ocurrió — se integrará en la memoria a largo plazo de su Junta IA.",
    "outcome.choice_label": "¿Qué opción eligió realmente?",
    "outcome.period_label": "¿Cuándo tomó esta decisión?",
    "outcome.satisfaction_label": "Puntuación de Satisfacción",
    "outcome.outcome_label": "¿Qué sucedió realmente?",
    "outcome.outcome_placeholder": "Describa el resultado real y compare con la predicción de la junta...",
    "outcome.lesson_label": "Lección Clave Aprendida",
    "outcome.lesson_placeholder": "¿Qué haría diferente? ¿Qué suposiciones eran correctas o incorrectas?",
    "outcome.save": "Guardar Retrospectiva en Memoria",
    "outcome.saving": "Integrando en Memoria Vectorial...",
    "outcome.close": "Cerrar",
    "debate.title": "Registro del Debate de Contrainterrogatorio",
    "debate.subtitle": "El debate dialéctico donde los asesores desafían las suposiciones del otro.",
    "debate.empty": "No hay turnos de debate registrados aún.",
    "debate.empty_desc": "Ejecute la deliberación del consejo para generar el debate.",
    "debate.turn": "Turno",
    "debate.challenge": "Desafío",
    "debate.rebuttal": "Réplica",
    "dash.loading": "Cargando archivo de decisiones...",
  },

  fr: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "Cockpit",
    "nav.new_decision": "Nouveau Dilemme",
    "nav.memory_vault": "Coffre de Mémoire",
    "nav.profile": "Profil & Valeurs",
    "nav.about": "Comment Ça Marche",
    "nav.sign_out": "Déconnexion",
    "nav.convening": "Quorum Actif",

    // Dashboard HUD
    "dash.welcome_title": "Intelligence Décisionnelle Exécutive",
    "dash.welcome_desc": "Moteur de débat dialectique multi-agents modélisant les gains asymétriques et la vitesse.",
    "dash.btn_new": "+ Convoquer le Conseil",
    "dash.total_dilemmas": "Dilemmes Totaux",
    "dash.binding_verdicts": "Verdicts Obligatoires",
    "dash.premortem_acc": "Précision Pré-Mortem",
    "dash.vector_learnings": "Mémoire ChromaDB",
    "dash.filter_all": "Tous les Dilemmes",
    "dash.filter_career": "Carrière & Transitions",
    "dash.filter_startup": "Startup & Capital",
    "dash.filter_engineering": "Tech & Ingénierie",
    "dash.filter_financial": "Finances & Capital",
    "dash.enter_boardroom": "▶ Entrer dans la Salle du Conseil",
    "dash.no_dilemmas": "Aucun dilemme stratégique trouvé dans cette catégorie.",
    "dash.no_dilemmas_sub": "Soumettez un dilemme pour réunir le conseil de 6 agents.",

    // Boardroom & Live Debate
    "board.title": "Session du Conseil d'Administration",
    "board.live_session": "Session Multi-Agents en Direct...",
    "board.dialectic": "Dialectique Active: Examen croisé sur 6 vecteurs stratégiques",
    "board.play_debate": "Lancer le Débat en Direct",
    "board.pause_debate": "Pause",
    "board.restart": "Recommencer",
    "board.memo_md": "Mémo (.md)",
    "board.export_pdf": "Exporter PDF 🖨️",
    "board.consensus_index": "Indice de Consensus",
    "board.speaking_now": "Intervient actuellement",
    "board.final_verdict": "RÉSOLUTION ET DIRECTIVE FINALE DU CONSEIL",
    "board.consensus_score": "Score de Consensus",
    "board.inspect_blueprint": "Inspecter la Feuille de Route Ci-Dessous ↓",

    // New Dilemma Page
    "new.title": "Convoquer le Conseil Exécutif",
    "new.desc": "Soumettez un dilemme stratégique pour examen par vos 6 conseillers IA.",
    "new.dilemma_label": "Titre du Dilemme Stratégique",
    "new.dilemma_placeholder": "ex: Devrais-je quitter Big Tech pour rejoindre une startup IA en tant qu'ingénieur fondateur?",
    "new.context_label": "Contexte & Contraintes",
    "new.context_placeholder": "Détails financiers, rémunération, equity, tolérance au risque...",
    "new.options_label": "Options Envisagées",
    "new.add_option": "+ Ajouter une Option Alternative",
    "new.category_label": "Domaine Stratégique",
    "new.btn_convene": "Convoquer le Conseil Complet (LangGraph) ➔",
    "new.convening": "Conseillers en Délibération...",

    // Profile Page
    "profile.title": "Profil Exécutif & Valeurs",
    "profile.desc": "Calibrez votre conseil d'administration selon votre expérience et vos valeurs.",
    "profile.resume_title": "Extracteur de CV par IA",
    "profile.resume_desc": "Téléversez votre CV PDF pour extraire automatiquement compétences et valeurs.",
    "profile.extract_btn": "Extraire le Profil par IA ⚡",
    "profile.extracting": "Analyse du CV...",
    "profile.save_btn": "Enregistrer le Profil",
    "profile.custom_seats": "Conseillers Personnalisés",
    "profile.add_seat": "+ Créer un Nouveau Conseiller",

    // Chat Copilot
    "chat.title": "Copilote DecisionOS",
    "chat.placeholder": "Demandez conseil en temps réel à votre conseil...",
    "chat.send": "Envoyer",

    // Hero Section
    "hero.badge": "Intelligence Stratégique Multi-Agents",
    "hero.headline": "Les décisions à forts enjeux exigent",
    "hero.headline_accent": "des perspectives diverses.",
    "hero.desc": "Au lieu d'un seul prompt IA, DecisionOS orchestre 6 conseillers exécutifs autonomes (PDG, DAF, CTO, Analyste Risques, Mentor, Président) qui analysent, débattent et synthétisent des recommandations.",
    "hero.btn_convene": "Convoquer une Nouvelle Réunion",
    "hero.btn_explore": "Explorer les Délibérations Actives",
    "hero.feat1_title": "6 Conseillers IA Autonomes",
    "hero.feat1_desc": "Évaluations parallèles du runway financier, de la vélocité tech, du potentiel asymétrique et des garde-fous risque.",
    "hero.feat2_title": "Audits Pré-Mortem des Risques",
    "hero.feat2_desc": "Identifie les modes de défaillance systémiques et établit des alertes à 90 jours avant d'exécuter.",
    "hero.feat3_title": "Mémoire Long Terme ChromaDB",
    "hero.feat3_desc": "Indexe les leçons rétrospectives réelles pour affiner continuellement les orientations stratégiques.",

    // New Decision Form (extended)
    "new.back": "Retour au Tableau de Bord",
    "new.load_template": "Charger un Modèle :",
    "new.tmpl_startup": "Startup vs Grande Entreprise",
    "new.tmpl_founder": "Transition Fondateur",
    "new.heading": "Convoquez votre Conseil d'Administration Personnel",
    "new.heading_desc": "Définissez votre dilemme stratégique. Votre Conseil IA analysera, débattra et synthétisera une recommandation.",
    "new.field_title": "Dilemme / Question Stratégique *",
    "new.field_context": "Contexte et Antécédents Complets *",
    "new.field_category": "Catégorie de Décision",
    "new.field_urgency": "Urgence",
    "new.field_risk": "Tolérance au Risque",
    "new.field_goal": "Objectif Stratégique Principal",
    "new.field_runway": "Runway Financier de Base",
    "new.options_heading": "Options et Alternatives Stratégiques",
    "new.options_desc": "Définissez les voies alternatives que le Conseil débattra et comparera.",
    "new.opt_label": "Intitulé / Nom de l'Option",
    "new.opt_desc": "Description de la Voie Stratégique",
    "new.opt_pros": "Avantages / Points Positifs",
    "new.opt_cons": "Risques / Points Négatifs",
    "new.add_pro": "+ Ajouter un Avantage",
    "new.add_con": "+ Ajouter un Risque",
    "new.remove_option": "Supprimer l'Option",

    // Memory Vault
    "vault.title": "Coffre de Mémoire à Long Terme",
    "vault.desc": "DecisionOS stocke des embeddings vectorisés de vos décisions passées pour que votre Conseil n'oublie jamais vos leçons.",
    "vault.search_placeholder": "Rechercher par dilemme, leçon ou thème de carrière...",
    "vault.search_btn": "Requête Sémantique",
    "vault.scanning": "Analyse du coffre vectoriel ChromaDB...",
    "vault.empty_title": "Aucune Mémoire Indexée Pour l'Instant",
    "vault.empty_desc": "Une fois les résultats enregistrés sur les décisions complètes, vos réflexions seront automatiquement intégrées ici.",
    "vault.choice_label": "Décision Exécutée",
    "vault.outcome_label": "Résultat Réel",
    "vault.lesson_label": "Leçon Stratégique Clé pour le Conseil",
    "vault.satisfaction": "Satisfaction",

    // About Page
    "about.badge": "Architecture du Système",
    "about.title": "Comment Fonctionne DecisionOS",
    "about.desc": "Un système d'orchestration LangGraph multi-agents où 6 conseillers IA spécialisés délibèrent indépendamment vos décisions à forts enjeux.",
    "about.get_started": "Convoquez votre Premier Conseil →",
    "about.step1_title": "Définissez votre Dilemme Stratégique",
    "about.step1_tag": "Étape d'Entrée",
    "about.step2_title": "Réunissez le Conseil Autonome",
    "about.step2_tag": "Délibération Parallèle",
    "about.step3_title": "Contre-Interrogatoire et Verdict du Président",
    "about.step3_tag": "Synthèse",
    "about.step4_title": "Journaliser les Résultats en Mémoire Vectorielle",
    "about.step4_tag": "Apprentissage Continu",
    "about.advisors_title": "Rencontrez vos 6 Conseillers IA",
    "about.faq_title": "Questions Fréquentes",
    "detail.back": "Retour au Tableau de Bord Exécutif",
    "detail.loading": "Convocation du Conseil d'Administration...",
    "detail.not_found": "Décision introuvable.",
    "detail.back_dash": "Retour au Tableau de Bord",
    "detail.verdict_rendered": "Verdict Rendu",
    "detail.awaiting": "En Attente de Délibération",
    "detail.urgency": "Urgence",
    "detail.risk_profile": "Profil de Risque",
    "detail.timeline": "Calendrier",
    "detail.log_retro": "Journaliser le Résultat Rétrospectif",
    "detail.update_retro": "Mettre à Jour la Rétrospective",
    "detail.reconvene": "Reconvoquer le Conseil",
    "detail.convene_boardroom": "Convoquer la Salle du Conseil",
    "detail.deliberating": "Quorum en Délibération...",
    "detail.tab_report": "Verdict Exécutif et Plan",
    "detail.tab_opinions": "Fiches de Score des Conseillers",
    "detail.tab_debate": "Débat de Contre-Interrogatoire",
    "detail.tab_chat": "Questions au Conseil",
    "detail.board_standby": "Le Conseil d'Administration est Prêt",
    "detail.board_standby_desc": "Cliquez pour lancer la simulation. Le PDG, DAF, CTO, Analyste Risques et Mentor analyseront indépendamment votre dilemme.",
    "detail.convene_now": "Réunir le Conseil IA Maintenant",
    "detail.deliberating_6": "Délibération avec 6 Personas IA...",
    "profile.heading": "Profil Exécutif et Valeurs Fondamentales",
    "profile.heading_desc": "Ces paramètres guident votre Conseil Personnel lors de chaque délibération stratégique.",
    "profile.upload_file": "Téléverser un Fichier",
    "profile.paste_text": "Coller le Texte",
    "profile.drag_drop": "Cliquez ou glissez votre CV ici",
    "profile.file_formats": "PDF, DOCX, TXT, MD pris en charge",
    "profile.auto_extract": "Auto-Extraire et Remplir le Profil",
    "profile.extracting_params": "Extraction des Paramètres...",
    "profile.extract_success": "Ingestion du Profil Terminée !",
    "profile.params_title": "Paramètres Stratégiques et Contrôles Manuels",
    "profile.params_desc": "Personnalisez et affinez vos paramètres manuellement.",
    "profile.manual_active": "ÉDITION MANUELLE ACTIVE",
    "profile.current_role": "Rôle Professionnel Actuel",
    "profile.career_goals_label": "Objectifs de Carrière et Vision à 5 Ans",
    "profile.financial_runway_label": "Runway Financier de Sécurité",
    "profile.risk_tolerance_label": "Tolérance au Risque par Défaut",
    "profile.core_values_label": "Valeurs Fondamentales et Principes",
    "profile.add_value_btn": "+ Ajouter une Valeur",
    "profile.personal_context_label": "Contexte Personnel et Situation de Vie",
    "profile.save_success": "Profil et Valeurs Fondamentales enregistrés avec succès.",
    "profile.saving": "Enregistrement...",
    "auth.login_title": "Bon Retour",
    "auth.login_subtitle": "Connectez-vous à votre cockpit DecisionOS",
    "auth.email": "Adresse E-mail",
    "auth.password": "Mot de Passe",
    "auth.sign_in": "Se Connecter",
    "auth.signing_in": "Authentification...",
    "auth.demo": "Démo",
    "auth.no_account": "Pas de compte ?",
    "auth.sign_up_link": "Créer un →",
    "auth.register_title": "Rejoindre DecisionOS",
    "auth.register_subtitle": "Créez votre compte de conseil IA exécutif",
    "auth.full_name": "Nom Complet",
    "auth.confirm_pass": "Confirmer le Mot de Passe",
    "auth.create_account": "Créer un Compte",
    "auth.creating": "Création du Compte...",
    "auth.have_account": "Déjà un compte ?",
    "auth.sign_in_link": "Se connecter →",
    "outcome.title": "Journaliser le Résultat Rétrospectif",
    "outcome.subtitle": "Enregistrez ce qui s'est réellement passé — cela sera intégré dans la mémoire à long terme de votre Conseil IA.",
    "outcome.choice_label": "Quelle option avez-vous réellement choisie ?",
    "outcome.period_label": "Quand avez-vous pris cette décision ?",
    "outcome.satisfaction_label": "Score de Satisfaction",
    "outcome.outcome_label": "Que s'est-il réellement passé ?",
    "outcome.outcome_placeholder": "Décrivez le résultat réel et comparez avec la prédiction du conseil...",
    "outcome.lesson_label": "Leçon Clé Apprise",
    "outcome.lesson_placeholder": "Qu'auriez-vous fait différemment ? Quelles hypothèses étaient justes ou fausses ?",
    "outcome.save": "Sauvegarder la Rétrospective en Mémoire",
    "outcome.saving": "Intégration en Mémoire Vectorielle...",
    "outcome.close": "Fermer",
    "debate.title": "Journal du Débat de Contre-Interrogatoire",
    "debate.subtitle": "Le débat dialectique où les conseillers défient les hypothèses des autres.",
    "debate.empty": "Aucun tour de débat enregistré.",
    "debate.empty_desc": "Lancez la délibération du conseil pour générer le débat.",
    "debate.turn": "Tour",
    "debate.challenge": "Défi",
    "debate.rebuttal": "Réfutation",
    "dash.loading": "Chargement de l'archive des décisions...",
  },

  de: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "Cockpit",
    "nav.new_decision": "Neues Dilemma",
    "nav.memory_vault": "Gedächtnistresor",
    "nav.profile": "Profil & Werte",
    "nav.about": "Wie es funktioniert",
    "nav.sign_out": "Abmelden",
    "nav.convening": "Aktives Quorum",

    // Dashboard HUD
    "dash.welcome_title": "Strategische Entscheidungsintelligenz",
    "dash.welcome_desc": "Multi-Agenten-Debatten-Engine zur Modellierung von asymmetrischem Ertrag und Runway.",
    "dash.btn_new": "+ Vorstand Einberufen",
    "dash.total_dilemmas": "Gesamte Dilemmata",
    "dash.binding_verdicts": "Verbindliche Urteile",
    "dash.premortem_acc": "Pre-Mortem Genauigkeit",
    "dash.vector_learnings": "ChromaDB Speicher",
    "dash.filter_all": "Alle Dilemmata",
    "dash.filter_career": "Karriere & Übergänge",
    "dash.filter_startup": "Startup & Wagnis",
    "dash.filter_engineering": "Tech & Engineering",
    "dash.filter_financial": "Finanzen & Kapital",
    "dash.enter_boardroom": "▶ Sitzungssaal Betreten",
    "dash.no_dilemmas": "Keine strategischen Dilemmata in dieser Kategorie gefunden.",
    "dash.no_dilemmas_sub": "Reichen Sie ein Dilemma ein, um den 6-köpfigen Vorstand einzuberufen.",

    // Boardroom & Live Debate
    "board.title": "Vorstandssitzung",
    "board.live_session": "Live-Vorstandssitzung Läuft...",
    "board.dialectic": "Aktive Dialektik: Kreuzverhör über 6 strategische Vektoren",
    "board.play_debate": "Live-Debatte Starten",
    "board.pause_debate": "Debatte Anhalten",
    "board.restart": "Neu Starten",
    "board.memo_md": "Memo (.md)",
    "board.export_pdf": "PDF Exportieren 🖨️",
    "board.consensus_index": "Konsens-Index",
    "board.speaking_now": "Spricht Gerade",
    "board.final_verdict": "ENDGÜLTIGER VORSTANDSBESCHLUSS",
    "board.consensus_score": "Konsens-Punktzahl",
    "board.inspect_blueprint": "Vollständigen Blueprint Prüfen ↓",

    // New Dilemma Page
    "new.title": "Vorstand Einberufen",
    "new.desc": "Reichen Sie ein wichtiges Dilemma zur Prüfung durch Ihren 6-Agenten-Vorstand ein.",
    "new.dilemma_label": "Titel des Strategischen Dilemmas",
    "new.dilemma_placeholder": "z.B. Sollte ich Big Tech verlassen, um Gründungsingenieur bei einem KI-Startup zu werden?",
    "new.context_label": "Kontext & Rahmenbedingungen",
    "new.context_placeholder": "Finanzielle Reichweite, Gehalt, Anteile, Risikotoleranz beschreiben...",
    "new.options_label": "Optionen zur Auswahl",
    "new.add_option": "+ Alternative Option Hinzufügen",
    "new.category_label": "Strategischer Bereich",
    "new.btn_convene": "Vollständigen Vorstand Einberufen (LangGraph) ➔",
    "new.convening": "Berater Beraten Parallel...",

    // Profile Page
    "profile.title": "Vorstandsprofil & Werte",
    "profile.desc": "Kalibrieren Sie Ihren Vorstand nach Ihrer Erfahrung und Ihren Werten.",
    "profile.resume_title": "KI-Lebenslauf-Extraktor",
    "profile.resume_desc": "Laden Sie Ihren Lebenslauf als PDF hoch, um Fähigkeiten und Werte zu extrahieren.",
    "profile.extract_btn": "Profil per KI Extrahieren ⚡",
    "profile.extracting": "Lebenslauf Wird Analysiert...",
    "profile.save_btn": "Kalibrierung Speichern",
    "profile.custom_seats": "Eigene Vorstandsmitglieder",
    "profile.add_seat": "+ Neues Mitglied Erstellen",

    // Chat Copilot
    "chat.title": "DecisionOS Vorstand-Copilot",
    "chat.placeholder": "Fragen Sie Ihren Vorstand in Echtzeit nach Rat...",
    "chat.send": "Senden",

    // Hero Section
    "hero.badge": "Multi-Agenten Strategische Intelligenz",
    "hero.headline": "Hochriskante Entscheidungen erfordern",
    "hero.headline_accent": "diverse Perspektiven.",
    "hero.desc": "Statt eines einzelnen KI-Prompts orchestriert DecisionOS 6 autonome Führungsberater (CEO, CFO, CTO, Risikoanalyst, Mentor, Vorsitzender), die Dilemmata analysieren, debattieren und Empfehlungen synthetisieren.",
    "hero.btn_convene": "Neue Vorstandssitzung Einberufen",
    "hero.btn_explore": "Aktive Beratungen Erkunden",
    "hero.feat1_title": "6 Autonome KI-Berater",
    "hero.feat1_desc": "Parallele Bewertungen zu finanziellem Runway, Tech-Geschwindigkeit, asymmetrischem Aufwärtspotenzial und Risikosicherungen.",
    "hero.feat2_title": "Pre-Mortem Risikoaudits",
    "hero.feat2_desc": "Identifiziert systemische Ausfallmodi und legt 90-Tage-Frühwarner fest, bevor Sie handeln.",
    "hero.feat3_title": "ChromaDB Langzeitgedächtnis",
    "hero.feat3_desc": "Indexiert reale Retrospektivlektionen zur kontinuierlichen Verfeinerung strategischer Beratung.",

    // New Decision Form (extended)
    "new.back": "Zurück zum Dashboard",
    "new.load_template": "Vorlage Laden:",
    "new.tmpl_startup": "Startup vs Großunternehmen",
    "new.tmpl_founder": "Gründer-Übergang",
    "new.heading": "Berufen Sie Ihren Persönlichen Vorstand Ein",
    "new.heading_desc": "Definieren Sie Ihr strategisches Dilemma. Ihr KI-Vorstand (CEO, CFO, CTO, Risikoanalyst, Mentor, Vorsitzender) analysiert, debattiert und synthetisiert eine Empfehlung.",
    "new.field_title": "Dilemma / Strategische Frage *",
    "new.field_context": "Vollständiger Hintergrund & Kontext *",
    "new.field_category": "Entscheidungskategorie",
    "new.field_urgency": "Dringlichkeit",
    "new.field_risk": "Risikobereitschaft",
    "new.field_goal": "Primäres Strategisches Ziel",
    "new.field_runway": "Finanzieller Basis-Runway",
    "new.options_heading": "Strategische Optionen & Alternativen",
    "new.options_desc": "Definieren Sie die alternativen Pfade, die der Vorstand debattieren und vergleichen wird.",
    "new.opt_label": "Options-Bezeichnung / Name",
    "new.opt_desc": "Beschreibung des Strategischen Pfades",
    "new.opt_pros": "Vorteile / Positive Aspekte",
    "new.opt_cons": "Risiken / Negative Aspekte",
    "new.add_pro": "+ Vorteil Hinzufügen",
    "new.add_con": "+ Risiko Hinzufügen",
    "new.remove_option": "Option Entfernen",

    // Memory Vault
    "vault.title": "Langzeit-Gedächtnistresor",
    "vault.desc": "DecisionOS speichert vektorisierte Einbettungen Ihrer vergangenen Entscheidungen, damit Ihr Vorstand nie frühere Blindstellen wiederholt.",
    "vault.search_placeholder": "Nach Dilemma, Lektion oder Karrierethema suchen...",
    "vault.search_btn": "Semantische Abfrage",
    "vault.scanning": "ChromaDB Vektortresor wird gescannt...",
    "vault.empty_title": "Noch Keine Historischen Erinnerungen Indiziert",
    "vault.empty_desc": "Sobald Sie retrospektive Ergebnisse zu abgeschlossenen Entscheidungen protokollieren, werden Ihre Reflexionen hier eingebettet.",
    "vault.choice_label": "Getroffene Entscheidung",
    "vault.outcome_label": "Tatsächliches Ergebnis",
    "vault.lesson_label": "Strategische Kernlektion für den Vorstand",
    "vault.satisfaction": "Zufriedenheit",

    // About Page
    "about.badge": "Systemarchitektur",
    "about.title": "Wie DecisionOS Funktioniert",
    "about.desc": "Ein Multi-Agenten LangGraph-Orchestrierungssystem, bei dem 6 spezialisierte KI-Berater Ihre hochriskanten Entscheidungen unabhängig voneinander erörtern.",
    "about.get_started": "Ersten Vorstand Einberufen →",
    "about.step1_title": "Strategisches Dilemma Definieren",
    "about.step1_tag": "Eingabephase",
    "about.step2_title": "Autonomen Vorstand Einberufen",
    "about.step2_tag": "Parallele Beratung",
    "about.step3_title": "Kreuzverhör und Urteil des Vorsitzenden",
    "about.step3_tag": "Synthese",
    "about.step4_title": "Ergebnisse in Vektorspeicher Protokollieren",
    "about.step4_tag": "Kontinuierliches Lernen",
    "about.advisors_title": "Lernen Sie Ihre 6 KI-Berater Kennen",
    "about.faq_title": "Häufig Gestellte Fragen",
    "detail.back": "Zurück zum Executiven Dashboard",
    "detail.loading": "Vorstandssitzung wird einberufen...",
    "detail.not_found": "Entscheidung nicht gefunden.",
    "detail.back_dash": "Zurück zum Dashboard",
    "detail.verdict_rendered": "Urteil Verkündet",
    "detail.awaiting": "Warte auf Beratung",
    "detail.urgency": "Dringlichkeit",
    "detail.risk_profile": "Risikoprofil",
    "detail.timeline": "Zeitplan",
    "detail.log_retro": "Retrospektives Ergebnis Protokollieren",
    "detail.update_retro": "Retrospektive Aktualisieren",
    "detail.reconvene": "Vorstand Erneut Einberufen",
    "detail.convene_boardroom": "Sitzungssaal Einberufen",
    "detail.deliberating": "Quorum Berät...",
    "detail.tab_report": "Executives Urteil & Blueprint",
    "detail.tab_opinions": "Einzelne Berater-Scorecards",
    "detail.tab_debate": "Kreuzverhör-Debatte",
    "detail.tab_chat": "Vorstand Befragen (Q&A)",
    "detail.board_standby": "Der Vorstand Ist Bereit",
    "detail.board_standby_desc": "Klicken Sie, um die Simulation zu starten. CEO, CFO, CTO, Risikoanalyst und Mentor analysieren Ihr Dilemma unabhängig voneinander.",
    "detail.convene_now": "KI-Vorstandssitzung Jetzt Einberufen",
    "detail.deliberating_6": "Beratung über 6 KI-Personas...",
    "profile.heading": "Vorstandsprofil & Grundwerte",
    "profile.heading_desc": "Diese Parameter leiten Ihren persönlichen Vorstand bei jeder strategischen Beratung.",
    "profile.upload_file": "Datei Hochladen",
    "profile.paste_text": "Text Einfügen",
    "profile.drag_drop": "Klicken oder Lebenslauf hierher ziehen",
    "profile.file_formats": "PDF, DOCX, TXT, MD unterstützt",
    "profile.auto_extract": "Profil Auto-Extrahieren & Ausfüllen",
    "profile.extracting_params": "Parameter Werden Extrahiert...",
    "profile.extract_success": "Profil-Erfassung Abgeschlossen!",
    "profile.params_title": "Strategische Parameter & Manuelle Steuerung",
    "profile.params_desc": "Passen Sie Ihre Parameter manuell an.",
    "profile.manual_active": "MANUELLE BEARBEITUNG AKTIV",
    "profile.current_role": "Aktuelle Berufsrolle & Fachbereich",
    "profile.career_goals_label": "Karriereziele & 5-Jahres-Vision",
    "profile.financial_runway_label": "Finanzieller Sicherheits-Runway",
    "profile.risk_tolerance_label": "Standard-Risikobereitschaft",
    "profile.core_values_label": "Kernwerte & Grundsätze",
    "profile.add_value_btn": "+ Wert Hinzufügen",
    "profile.personal_context_label": "Persönlicher Kontext & Lebenssituation",
    "profile.save_success": "Strategisches Profil & Kernwerte erfolgreich gespeichert.",
    "profile.saving": "Speichern...",
    "auth.login_title": "Willkommen Zurück",
    "auth.login_subtitle": "Melden Sie sich in Ihrem DecisionOS-Cockpit an",
    "auth.email": "E-Mail-Adresse",
    "auth.password": "Passwort",
    "auth.sign_in": "Anmelden",
    "auth.signing_in": "Authentifizierung...",
    "auth.demo": "Demo",
    "auth.no_account": "Kein Konto?",
    "auth.sign_up_link": "Erstellen →",
    "auth.register_title": "DecisionOS Beitreten",
    "auth.register_subtitle": "Erstellen Sie Ihr KI-Vorstandskonto",
    "auth.full_name": "Vollständiger Name",
    "auth.confirm_pass": "Passwort Bestätigen",
    "auth.create_account": "Konto Erstellen",
    "auth.creating": "Konto Wird Erstellt...",
    "auth.have_account": "Bereits ein Konto?",
    "auth.sign_in_link": "Anmelden →",
    "outcome.title": "Retrospektives Ergebnis Protokollieren",
    "outcome.subtitle": "Zeichnen Sie auf, was wirklich passiert ist — es wird in das Langzeitgedächtnis Ihres KI-Vorstands eingebettet.",
    "outcome.choice_label": "Welche Option haben Sie tatsächlich gewählt?",
    "outcome.period_label": "Wann haben Sie diese Entscheidung getroffen?",
    "outcome.satisfaction_label": "Zufriedenheitswert",
    "outcome.outcome_label": "Was ist tatsächlich passiert?",
    "outcome.outcome_placeholder": "Beschreiben Sie das reale Ergebnis und vergleichen Sie mit der Vorhersage des Vorstands...",
    "outcome.lesson_label": "Wichtigste Gelernde Lektion",
    "outcome.lesson_placeholder": "Was würden Sie anders machen? Welche Annahmen waren richtig oder falsch?",
    "outcome.save": "Retrospektive in Gedächtnis Speichern",
    "outcome.saving": "In Vektorspeicher Einbetten...",
    "outcome.close": "Schließen",
    "debate.title": "Kreuzverhör-Debatte Protokoll",
    "debate.subtitle": "Die dialektische Debatte, bei der Berater die Annahmen des anderen herausfordern.",
    "debate.empty": "Noch keine Debattenrunden aufgezeichnet.",
    "debate.empty_desc": "Starten Sie die Vorstandsberatung, um die Debatte zu generieren.",
    "debate.turn": "Runde",
    "debate.challenge": "Herausforderung",
    "debate.rebuttal": "Widerlegung",
    "dash.loading": "Entscheidungsarchiv Wird Geladen...",
  },

  ja: {
    // Navigation
    "nav.brand": "decisionos",
    "nav.dashboard": "コックピット",
    "nav.new_decision": "新しい決断 (Dilemma)",
    "nav.memory_vault": "記憶保管庫 (Memory)",
    "nav.profile": "プロフィールと価値観",
    "nav.about": "ご利用ガイド (How It Works)",
    "nav.sign_out": "ログアウト",
    "nav.convening": "取締役会開催中",

    // Dashboard HUD
    "dash.welcome_title": "エグゼクティブ意思決定インテリジェンス",
    "dash.welcome_desc": "非対称な利益、財務リスク、スキルの成長速度をモデル化するマルチエージェント対話エンジン。",
    "dash.btn_new": "+ 取締役会を招集",
    "dash.total_dilemmas": "総ジレンマ数",
    "dash.binding_verdicts": "最終決定数",
    "dash.premortem_acc": "事前検証精度",
    "dash.vector_learnings": "ChromaDB 学習蓄積",
    "dash.filter_all": "すべての決断",
    "dash.filter_career": "キャリアと転職",
    "dash.filter_startup": "スタートアップと事業",
    "dash.filter_engineering": "技術と開発",
    "dash.filter_financial": "財務と資本",
    "dash.enter_boardroom": "▶ ライブ取締役会に入室",
    "dash.no_dilemmas": "このカテゴリに戦略的ジレンマはありません。",
    "dash.no_dilemmas_sub": "ジレンマを送信して6名の顧問エージェントを招集してください。",

    // Boardroom & Live Debate
    "board.title": "エグゼクティブ取締役会セッション",
    "board.live_session": "マルチエージェント取締役会 審議中...",
    "board.dialectic": "能動的弁証法：6つの戦略的視点からの徹底検証",
    "board.play_debate": "ライブ議論を再生",
    "board.pause_debate": "議論を一時停止",
    "board.restart": "最初から再生",
    "board.memo_md": "メモ (.md)",
    "board.export_pdf": "PDF出力 🖨️",
    "board.consensus_index": "取締役会合意指数",
    "board.speaking_now": "発言中",
    "board.final_verdict": "取締役会 最終決議および指示",
    "board.consensus_score": "合意スコア",
    "board.inspect_blueprint": "実行計画の詳細を確認 ↓",

    // New Dilemma Page
    "new.title": "エグゼクティブ取締役会の招集",
    "new.desc": "6名のエージェントによる厳密な検証のため、重要案件を提出してください。",
    "new.dilemma_label": "戦略的ジレンマの件名",
    "new.dilemma_placeholder": "例: 大手テック企業を辞めてAIスタートアップの初期エンジニアに参加すべきか？",
    "new.context_label": "背景と制約条件",
    "new.context_placeholder": "財務的猶予、報酬、株式、リスク許容度、トレードオフを記述...",
    "new.options_label": "検討中の選択肢",
    "new.add_option": "+ 代替案を追加",
    "new.category_label": "戦略領域",
    "new.btn_convene": "取締役会全員を招集 (LangGraph) ➔",
    "new.convening": "顧問陣が並行して審議中...",

    // Profile Page
    "profile.title": "エグゼクティブ プロファイルと価値観",
    "profile.desc": "あなたの経歴、リスク許容度、理念に合わせて取締役会を調整します。",
    "profile.resume_title": "AI 職務経歴書・スキル抽出",
    "profile.resume_desc": "PDFをアップロードするかテキストを貼り付けて、経歴とスキルを自動抽出します。",
    "profile.extract_btn": "AIでプロファイルを抽出 ⚡",
    "profile.extracting": "経歴書を解析中...",
    "profile.save_btn": "調整内容を保存",
    "profile.custom_seats": "カスタム顧問席とペルソナ",
    "profile.add_seat": "+ 新しい顧問席を作成",

    // Chat Copilot
    "chat.title": "DecisionOS 取締役会コパイロット",
    "chat.placeholder": "AI取締役会にリアルタイムの戦略的助言を求める...",
    "chat.send": "送信",

    // Hero Section
    "hero.badge": "マルチエージェント戦略インテリジェンス",
    "hero.headline": "高リスクの意思決定には",
    "hero.headline_accent": "多様な視点が必要です。",
    "hero.desc": "単一のAIプロンプトの代わりに、DecisionOSは6名の自律的なエグゼクティブアドバイザー（CEO、CFO、CTO、リスクアナリスト、メンター、会長）を統合し、ジレンマを分析・討議して行動可能なロードマップを合成します。",
    "hero.btn_convene": "新しい取締役会を招集",
    "hero.btn_explore": "進行中の審議を見る",
    "hero.feat1_title": "6名の自律AIアドバイザー",
    "hero.feat1_desc": "財務ランウェイ、技術速度、非対称な上昇余地、リスク保護にわたる並行評価。",
    "hero.feat2_title": "プレモーテム リスク監査",
    "hero.feat2_desc": "システム的な失敗モードを特定し、実行前に90日のトリップワイヤーを設定します。",
    "hero.feat3_title": "ChromaDB 長期記憶",
    "hero.feat3_desc": "過去の経験を蓄積し、将来の戦略的助言を継続的に洗練します。",

    // New Decision Form (extended)
    "new.back": "ダッシュボードに戻る",
    "new.load_template": "テンプレートを読み込む:",
    "new.tmpl_startup": "スタートアップ vs 大企業",
    "new.tmpl_founder": "創業者への転換",
    "new.heading": "パーソナル取締役会を招集する",
    "new.heading_desc": "戦略的ジレンマと選択肢を定義してください。AIボード（CEO、CFO、CTO、リスクアナリスト、メンター、会長）が分析・討議し、推奨事項を合成します。",
    "new.field_title": "意思決定のジレンマ / 質問 *",
    "new.field_context": "詳細な背景とコンテキスト *",
    "new.field_category": "意思決定カテゴリ",
    "new.field_urgency": "緊急度",
    "new.field_risk": "リスク許容度",
    "new.field_goal": "主要な戦略目標",
    "new.field_runway": "財務基盤ランウェイ",
    "new.options_heading": "戦略的選択肢と代替案",
    "new.options_desc": "取締役会が討議・比較する代替案を定義してください。",
    "new.opt_label": "選択肢のラベル / 名前",
    "new.opt_desc": "戦略的パスの説明",
    "new.opt_pros": "メリット / プラス面",
    "new.opt_cons": "リスク / マイナス面",
    "new.add_pro": "+ メリットを追加",
    "new.add_con": "+ リスクを追加",
    "new.remove_option": "選択肢を削除",

    // Memory Vault
    "vault.title": "長期記憶保管庫",
    "vault.desc": "DecisionOSは過去の意思決定、選択、振り返りの教訓をベクトル化して保存します。新しいジレンマが発生した際、取締役会は意味論的な知恵を抽出して盲点を繰り返さないようにします。",
    "vault.search_placeholder": "ジレンマ、教訓、またはキャリアテーマで検索...",
    "vault.search_btn": "セマンティック検索",
    "vault.scanning": "ChromaDB ベクターボールトをスキャン中...",
    "vault.empty_title": "まだ記憶がインデックスされていません",
    "vault.empty_desc": "完了した意思決定に結果を記録すると、振り返りが将来の取締役会セッションのためにここに自動埋め込みされます。",
    "vault.choice_label": "実行した選択",
    "vault.outcome_label": "実際の結果",
    "vault.lesson_label": "取締役会への主要な戦略的教訓",
    "vault.satisfaction": "満足度",

    // About Page
    "about.badge": "システムアーキテクチャ",
    "about.title": "DecisionOSの仕組み",
    "about.desc": "6名の専門AIアドバイザーが独立して高リスクの意思決定を審議するマルチエージェントLangGraphオーケストレーションシステム。",
    "about.get_started": "最初の取締役会を招集する →",
    "about.step1_title": "戦略的ジレンマを定義する",
    "about.step1_tag": "入力段階",
    "about.step2_title": "自律取締役会を招集する",
    "about.step2_tag": "並行審議",
    "about.step3_title": "反対尋問と会長の裁定",
    "about.step3_tag": "統合",
    "about.step4_title": "ベクターメモリに結果を記録する",
    "about.step4_tag": "継続的学習",
    "about.advisors_title": "6名のAIアドバイザーに会う",
    "about.faq_title": "よくある質問",
    "detail.back": "エグゼクティブダッシュボードに戻る",
    "detail.loading": "取締役会ブリーフィングを招集中...",
    "detail.not_found": "意思決定が見つかりません。",
    "detail.back_dash": "ダッシュボードに戻る",
    "detail.verdict_rendered": "裁定済み",
    "detail.awaiting": "審議待ち",
    "detail.urgency": "緊急度",
    "detail.risk_profile": "リスクプロファイル",
    "detail.timeline": "タイムライン",
    "detail.log_retro": "振り返り結果を記録",
    "detail.update_retro": "振り返りを更新",
    "detail.reconvene": "取締役会を再招集",
    "detail.convene_boardroom": "取締役会を招集",
    "detail.deliberating": "定足数審議中...",
    "detail.tab_report": "エグゼクティブ裁定と計画",
    "detail.tab_opinions": "個別アドバイザースコアカード",
    "detail.tab_debate": "反対尋問ディベート",
    "detail.tab_chat": "取締役会への質問",
    "detail.board_standby": "取締役会は準備完了です",
    "detail.board_standby_desc": "クリックしてシミュレーションを開始してください。CEO、CFO、CTO、リスクアナリスト、メンターが独立してジレンマを分析します。",
    "detail.convene_now": "AI取締役会を今すぐ招集",
    "detail.deliberating_6": "6名のAIペルソナで審議中...",
    "profile.heading": "エグゼクティブプロファイルと基本価値観",
    "profile.heading_desc": "これらのパラメータがすべての戦略的審議においてパーソナル取締役会を導きます。",
    "profile.upload_file": "ファイルをアップロード",
    "profile.paste_text": "テキストを貼り付け",
    "profile.drag_drop": "クリックまたは履歴書をここにドラッグ",
    "profile.file_formats": "PDF、DOCX、TXT、MD対応",
    "profile.auto_extract": "プロファイルを自動抽出・入力",
    "profile.extracting_params": "パラメータを抽出中...",
    "profile.extract_success": "プロファイル取り込み完了！",
    "profile.params_title": "戦略的パラメータと手動コントロール",
    "profile.params_desc": "パラメータを手動でカスタマイズして調整してください。",
    "profile.manual_active": "手動編集モード",
    "profile.current_role": "現在の職業的役割とドメインフォーカス",
    "profile.career_goals_label": "キャリア目標と5年ビジョン",
    "profile.financial_runway_label": "財務安全ランウェイ",
    "profile.risk_tolerance_label": "デフォルトリスク許容度",
    "profile.core_values_label": "基本価値観と原則",
    "profile.add_value_btn": "+ 価値観を追加",
    "profile.personal_context_label": "個人的文脈と生活状況",
    "profile.save_success": "戦略的プロファイルと基本価値観が正常に保存されました。",
    "profile.saving": "保存中...",
    "auth.login_title": "おかえりなさい",
    "auth.login_subtitle": "DecisionOSコックピットにサインイン",
    "auth.email": "メールアドレス",
    "auth.password": "パスワード",
    "auth.sign_in": "サインイン",
    "auth.signing_in": "認証中...",
    "auth.demo": "デモ",
    "auth.no_account": "アカウントがない？",
    "auth.sign_up_link": "作成する →",
    "auth.register_title": "DecisionOSに参加",
    "auth.register_subtitle": "エグゼクティブAI取締役会アカウントを作成",
    "auth.full_name": "フルネーム",
    "auth.confirm_pass": "パスワードを確認",
    "auth.create_account": "アカウント作成",
    "auth.creating": "アカウント作成中...",
    "auth.have_account": "すでにアカウントをお持ちですか？",
    "auth.sign_in_link": "サインイン →",
    "outcome.title": "振り返り結果を記録",
    "outcome.subtitle": "実際に何が起こったかを記録してください — AIボードの長期記憶に埋め込まれます。",
    "outcome.choice_label": "実際にどの選択肢を選びましたか？",
    "outcome.period_label": "この決断をいつ下しましたか？",
    "outcome.satisfaction_label": "満足度スコア",
    "outcome.outcome_label": "実際に何が起こりましたか？",
    "outcome.outcome_placeholder": "実際の結果を説明し、取締役会の予測と比較してください...",
    "outcome.lesson_label": "学んだ主要な教訓",
    "outcome.lesson_placeholder": "何を違うようにしますか？どの仮定が正しくて間違っていましたか？",
    "outcome.save": "振り返りをメモリに保存",
    "outcome.saving": "ベクターメモリに埋め込み中...",
    "outcome.close": "閉じる",
    "debate.title": "反対尋問ディベートログ",
    "debate.subtitle": "アドバイザーが互いの仮定に挑戦する生きたディベート。",
    "debate.empty": "まだディベートターンが記録されていません。",
    "debate.empty_desc": "取締役会審議を実行してディベートを生成してください。",
    "debate.turn": "ターン",
    "debate.challenge": "挑戦",
    "debate.rebuttal": "反論",
    "dash.loading": "意思決定アーカイブを読み込み中...",
  }
};

export const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  currentLanguageConfig: SUPPORTED_LANGUAGES[0],
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem("decisionos_lang") || "en";
  });

  const setLanguage = (langCode) => {
    playClickSound();
    setLanguageState(langCode);
    localStorage.setItem("decisionos_lang", langCode);
  };

  const t = (key, fallback) => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || fallback || key;
  };

  const currentLanguageConfig = SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageConfig, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
